# Generated by Django 5.1.3 on 2024-12-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_comment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="object_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="product.product",
            ),
        ),
    ]
