# Generated by Django 5.1.3 on 2024-12-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_rename_is_active_product_in_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
